const Constants = {
  USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
  USER_SIGN_UP_REQUEST: 'USER_SIGN_UP_REQUEST',
  USER_SIGN_UP_FAILURE: 'USER_SIGN_UP_FAILURE',

  USER_SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',
  USER_SIGN_IN_REQUEST: 'USER_SIGN_IN_REQUEST',
  USER_SIGN_IN_FAILURE: 'USER_SIGN_IN_FAILURE',
};

export default Constants;
