const Constants = {
  SESSION_RESET: 'SESSION_RESET',

  USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
  USER_SIGN_UP_REQUEST: 'USER_SIGN_UP_REQUEST',
  USER_SIGN_UP_FAILURE: 'USER_SIGN_UP_FAILURE',

  USER_SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',
  USER_SIGN_IN_REQUEST: 'USER_SIGN_IN_REQUEST',
  USER_SIGN_IN_FAILURE: 'USER_SIGN_IN_FAILURE',

  CURRENT_USER: 'CURRENT_USER',
  CURRENT_USER_FAILURE: 'CURRENT_USER_FAILURE',

  FETCH_BOARDS: 'FETCH_BOARDS',
  FETCH_BOARDS_FAILURE: 'FETCH_BOARDS_FAILURE',

  ADD_NEW_BOARD_SUCCESS: 'ADD_NEW_BOARD_SUCCESS',
  ADD_NEW_BOARD_FAILURE: 'ADD_NEW_BOARD_FAILURE',
};

export default Constants;
